# Utility functions for building intent-based analysis functions from transcripts and R code.

sanitize_function_name <- function(title) {
  fn <- tolower(title)
  fn <- gsub("[^a-z0-9]+", " ", fn)
  fn <- gsub("\\b(r|rmd|txt|the|a|an|and|with|in|of|for|to|on|us|our|tidy|tuesday|dataset|data|analysis|analyzing)\\b", " ", fn)
  fn <- gsub("\\s+", " ", fn)
  fn <- trimws(fn)
  fn <- gsub(" ", "_", fn)
  if (grepl("^[0-9]", fn)) {
    fn <- paste0("x_", fn)
  }
  fn
}

normalize_control_table_schema <- function(control) {
  optional_columns <- c(
    "function_name",
    "data_source",
    "analysis_intent",
    "analysis_type",
    "pattern_signature",
    "adaptation_hint",
    "ker_status",
    "notes"
  )

  for (column_name in optional_columns) {
    if (!column_name %in% names(control)) {
      control[[column_name]] <- ""
    }
  }

  control
}

load_control_table <- function(path = "control_table.csv") {
  if (!file.exists(path)) {
    stop("control table not found: ", path)
  }

  control <- read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)

  required_columns <- c("transcript_title", "transcript_file", "code_file")
  if (!all(required_columns %in% names(control))) {
    stop(
      "control table must contain columns: ",
      paste(required_columns, collapse = ", ")
    )
  }

  normalize_control_table_schema(control)
}

resolve_function_name <- function(title, function_name = "") {
  if (!is.null(function_name) && nzchar(trimws(function_name))) {
    trimws(function_name)
  } else {
    sanitize_function_name(title)
  }
}

field_or_empty <- function(value) {
  if (length(value) == 0 || is.na(value) || !nzchar(trimws(value))) {
    ""
  } else {
    trimws(value)
  }
}

intent_function_header <- function(name, title, code_file, metadata = list()) {
  description <- "#' @description Intent-based analysis function derived from screencast transcript and code."

  header <- c(
    sprintf("#' %s", title),
    description,
    sprintf("#' @details Code file: %s", code_file),
    if (nzchar(metadata$data_source)) sprintf("#' @note Data source: %s", metadata$data_source) else NULL,
    if (nzchar(metadata$analysis_intent)) sprintf("#' @note Analysis intent: %s", metadata$analysis_intent) else NULL,
    if (nzchar(metadata$analysis_type)) sprintf("#' @note Analysis type: %s", metadata$analysis_type) else NULL,
    if (nzchar(metadata$pattern_signature)) sprintf("#' @note Pattern signature: %s", metadata$pattern_signature) else NULL,
    if (nzchar(metadata$adaptation_hint)) sprintf("#' @note Adaptation hint: %s", metadata$adaptation_hint) else NULL,
    if (nzchar(metadata$ker_status)) sprintf("#' @note KER status: %s", metadata$ker_status) else NULL,
    if (nzchar(metadata$notes)) sprintf("#' @note %s", metadata$notes) else NULL,
    "#' @param data A data.frame or tibble containing the dataset to analyze.",
    "#' @param ... Additional arguments passed to lower-level helpers.",
    "#' @return A list or tibble containing analysis results.",
    "#' @export",
    sprintf("%s <- function(data, ...) {", name),
    sprintf("  stop(\"Not implemented: intent-based analysis for '%s'\")", title),
    "}",
    ""
  )

  paste(header, collapse = "\n")
}

control_table_iteration_queue <- function(control_file = "control_table.csv",
                                          pending_only = TRUE) {
  control <- load_control_table(control_file)

  if (!pending_only) {
    return(control)
  }

  pending_status <- c("", "needs_mapping", "mapped", "extracted", "implemented")
  control[is.na(control$ker_status) | control$ker_status %in% pending_status, , drop = FALSE]
}

build_intent_function_stubs <- function(control_file = "control_table.csv",
                                        output_path = "R/screencast_intent_stubs.R") {
  control <- load_control_table(control_file)

  lines <- c(
    "# Auto-generated stub functions for transcript intent analysis",
    "# Generated by R/intents.R",
    ""
  )

  for (i in seq_len(nrow(control))) {
    title <- control$transcript_title[i]
    code_file <- field_or_empty(control$code_file[i])
    if (!nzchar(code_file)) {
      code_file <- "(no matched code file)"
    }

    fn <- resolve_function_name(
      title = title,
      function_name = field_or_empty(control$function_name[i])
    )

    metadata <- list(
      data_source = field_or_empty(control$data_source[i]),
      analysis_intent = field_or_empty(control$analysis_intent[i]),
      analysis_type = field_or_empty(control$analysis_type[i]),
      pattern_signature = field_or_empty(control$pattern_signature[i]),
      adaptation_hint = field_or_empty(control$adaptation_hint[i]),
      ker_status = field_or_empty(control$ker_status[i]),
      notes = field_or_empty(control$notes[i])
    )

    lines <- c(lines, intent_function_header(fn, title, code_file, metadata))
  }

  writeLines(lines, con = output_path)
  message("Wrote ", output_path)
}
